[cts-circulars]
title = "CTS Circulars"
url = "https://www.npci.org.in/what-we-do/cts/circulars"
entrySelector = ".pdf-item"
titleSelector = "p"
linkSelector = "a"
timeout = 10

[upi-circulars]
title = "UPI Circulars"
url = "https://www.npci.org.in/what-we-do/upi/circular"
entrySelector = ".pdf-item"
titleSelector = "p"
timeout = 10