name: publish

on:
  push:
    branches:
      - main
  schedule:
    # Optimize for Indian working hours
    # Runs at 8:09 UTC = 13:39 IST
    # Runs at 12:09 UTC = 17:39 IST
    - cron: '09 8,12 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: php generate.php
        name: Set current Year
      - uses: r7kamura/weneedfeed-action@v3.6.0
        with:
          base_url: https://captnemo.in/npci-rss-feeds
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output